services:
  - type: web
    name: makonome
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: VECTORDB_SUPABASE_URL
        sync: false
      - key: VECTORDB_SUPABASE_ANON_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.8
    autoDeploy: true