services:
  - type: web
    name: makonome
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: VECTORDB_SUPABASE_URL
        sync: false
      - key: VECTORDB_SUPABASE_ANON_KEY
        sync: false
      - key: BALANCEFLOW_SUPABASE_URL
        sync: false
      - key: BALANCEFLOW_SUPABASE_ANON_KEY
        sync: false
      - key: MAKO_DASH_TOKEN
        sync: false
      - key: MAKO_NTFY_TOPIC
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MAKO_TELEGRAM_BOT_TOKEN
        sync: false
      - key: MAKO_TELEGRAM_CHAT_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.8
    autoDeploy: true